### ISSUE TITLE
Shouldn't attempt to follow ES6 backticks

### ISSUE THREAD

**Issue by AlexChesters** [octo-linker/chrome-extension#60]
I've found that ES6 [template string](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/template_strings) can be selected using this extension. You can see an example of this [here](https://github.com/AlexChesters/alexchesters.com/blob/master/lib/app.js#L27).

**Comment by stefanbuck** [comment]
Thanks for reporting the issue. I've noticed the same behaviour a couple of times, but since I started working on the next major version I don't want waste time on fixing it :wink:
